require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'

AllCops:
  NewCops: enable
  Exclude:
    - 'config/initializers/devise.rb'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'Guardfile'
    - 'spec/**/*'
